export enum QUERY_KEYS {
  TREND_LIST = 'TREND_LIST',
  NOWPLAYING_LIST = 'NOWPLAYING_LIST',
  TOP_RATED_LIST = 'TOP_RATED_LIST',
  SEARCH_MULTI_LIST = 'SEARCH_MULTI_LIST',
  SEARCH_MOVIES_LIST = 'SEARCH_MOVIES_LIST',
  POPULAR_MOVIES_LIST = 'POPULAR_MOVIES_LIST',
}
